version: '3.4'
services:
  app:
    container_name: Api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./app:/publish
    depends_on:
      - database
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
    - ${POSTGRES_HOST}:${POSTGRES_HOST}
    volumes:
    - ./app/data:/data/database

volumes: {}